# Generated by Django 3.2.6 on 2024-08-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea_financiera',
            name='TF_BMILESTONE',
            field=models.BooleanField(default=False, verbose_name='Es un hito'),
        ),
        migrations.AddField(
            model_name='tarea_financiera',
            name='TF_NDURACION_PLANIFICADA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Duración planificada (horas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea_financiera',
            name='TF_NDURACION_REAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duración real (horas)'),
        ),
        migrations.AddField(
            model_name='tarea_financiera',
            name='TF_NPROGRESO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progreso (%)'),
        ),
        migrations.AddField(
            model_name='tarea_financiera',
            name='TG_BCRITICA',
            field=models.BooleanField(default=False, verbose_name='En la ruta crítica'),
        ),
        migrations.AddField(
            model_name='tarea_general',
            name='TG_BCRITICA',
            field=models.BooleanField(default=False, verbose_name='En la ruta crítica'),
        ),
        migrations.AddField(
            model_name='tarea_general',
            name='TG_BMILESTONE',
            field=models.BooleanField(default=False, verbose_name='Es un hito'),
        ),
        migrations.AddField(
            model_name='tarea_general',
            name='TG_NDURACION_PLANIFICADA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Duración planificada (horas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea_general',
            name='TG_NDURACION_REAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duración real (horas)'),
        ),
        migrations.AddField(
            model_name='tarea_general',
            name='TG_NPROGRESO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progreso (%)'),
        ),
        migrations.AddField(
            model_name='tarea_ingenieria',
            name='TG_BCRITICA',
            field=models.BooleanField(default=False, verbose_name='En la ruta crítica'),
        ),
        migrations.AddField(
            model_name='tarea_ingenieria',
            name='TI_BMILESTONE',
            field=models.BooleanField(default=False, verbose_name='Es un hito'),
        ),
        migrations.AddField(
            model_name='tarea_ingenieria',
            name='TI_NDURACION_PLANIFICADA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Duración planificada (horas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea_ingenieria',
            name='TI_NDURACION_REAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duración real (horas)'),
        ),
        migrations.AddField(
            model_name='tarea_ingenieria',
            name='TI_NPROGRESO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progreso (%)'),
        ),
        migrations.AlterField(
            model_name='acta_reunion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adjunto_etapa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adjunto_tarea_financiera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adjunto_tarea_general',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adjunto_tarea_ingenieria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_contratista_tarea_financiera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_contratista_tarea_general',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_contratista_tarea_ingenieria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_financiera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_general',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_ingenieria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_recurso_tarea_financiera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_recurso_tarea_general',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion_recurso_tarea_ingenieria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boleta_garantia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria_cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria_proyecto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contacto_cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contratista_adjunto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contrato_cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='direccion_cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado_adjunto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado_contratista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado_contratista_adjunto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orden_venta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orden_venta_detalle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permiso_rol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyecto_adjunto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyecto_cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='system_log',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarea_financiera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarea_general',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarea_ingenieria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipo_proyecto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario_rol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TAREA_INGENIERIA_DEPENDENCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TD_TIPO_DEPENDENCIA', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], max_length=20)),
                ('TD_TAREA_PREDECESORA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras', to='home.tarea_ingenieria')),
                ('TD_TAREA_SUCESORA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecesoras', to='home.tarea_ingenieria')),
            ],
            options={
                'verbose_name': 'Dependencia de Tarea de Ingeniería',
                'verbose_name_plural': 'Dependencias de Tareas de Ingeniería',
                'db_table': 'TAREA_INGENIERIA_DEPENDENCIA',
            },
        ),
        migrations.CreateModel(
            name='TAREA_GENERAL_DEPENDENCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TD_TIPO_DEPENDENCIA', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], max_length=20)),
                ('TD_TAREA_PREDECESORA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras', to='home.tarea_general')),
                ('TD_TAREA_SUCESORA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecesoras', to='home.tarea_general')),
            ],
            options={
                'verbose_name': 'Dependencia de Tarea General',
                'verbose_name_plural': 'Dependencias de Tareas Generales',
                'db_table': 'TAREA_GENERAL_DEPENDENCIA',
            },
        ),
        migrations.CreateModel(
            name='TAREA_FINANCIERA_DEPENDENCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TD_TIPO_DEPENDENCIA', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], max_length=20)),
                ('TD_TAREA_PREDECESORA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras', to='home.tarea_financiera')),
                ('TD_TAREA_SUCESORA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecesoras', to='home.tarea_financiera')),
            ],
            options={
                'verbose_name': 'Dependencia de Tarea Financiera',
                'verbose_name_plural': 'Dependencias de Tareas Financieras',
                'db_table': 'TAREA_FINANCIERA_DEPENDENCIA',
            },
        ),
    ]
