# Generated by Django 3.2.6 on 2024-08-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240806_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='EM_CRUT',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='empleado_contratista',
            name='EC_CRUT',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT'),
        ),
    ]
