# Generated by Django 5.0.4 on 2024-08-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240807_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea_financiera',
            name='TF_PROYECTO_CLIENTE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_financieras_proyecto', to='home.proyecto_cliente', verbose_name='Proyecto de Cliente'),
        ),
        migrations.AddField(
            model_name='tarea_general',
            name='TG_PROYECTO_CLIENTE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_generales_proyecto', to='home.proyecto_cliente', verbose_name='Proyecto de Cliente'),
        ),
        migrations.AddField(
            model_name='tarea_ingenieria',
            name='TI_PROYECTO_CLIENTE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_ingenieria_proyecto', to='home.proyecto_cliente', verbose_name='Proyecto de Cliente'),
        ),
    ]
