# Generated by Django 5.0.4 on 2024-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_proyecto_cliente_pc_ccodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea_financiera',
            name='TF_CCODIGO',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código de tarea financiera'),
        ),
        migrations.AlterField(
            model_name='tarea_general',
            name='TG_CCODIGO',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código de tarea general'),
        ),
        migrations.AlterField(
            model_name='tarea_ingenieria',
            name='TI_CCODIGO',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código de tarea de ingeniería'),
        ),
    ]
