# Generated by Django 5.0.4 on 2024-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_asignacion_empleado_contratista_tarea_financiera_aec_costo_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_empleado_contratista_tarea_financiera',
            name='AEC_COSTO_TOTAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Total'),
        ),
        migrations.AddField(
            model_name='asignacion_empleado_contratista_tarea_general',
            name='AEC_COSTO_TOTAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Total'),
        ),
        migrations.AddField(
            model_name='asignacion_empleado_contratista_tarea_ingenieria',
            name='AEC_COSTO_TOTAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Total'),
        ),
        migrations.AddField(
            model_name='asignacion_empleado_tarea_financiera',
            name='AE_COSTO_TOTAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Total'),
        ),
        migrations.AddField(
            model_name='asignacion_empleado_tarea_general',
            name='AE_COSTO_TOTAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Total'),
        ),
        migrations.AddField(
            model_name='asignacion_empleado_tarea_ingenieria',
            name='AE_COSTO_TOTAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_financiera',
            name='AE_COSTO_REAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Real'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_general',
            name='AE_COSTO_REAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Real'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_ingenieria',
            name='AE_COSTO_REAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo Real'),
        ),
    ]
