# Generated by Django 5.0.4 on 2024-08-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_asignacion_empleado_contratista_tarea_financiera_aec_costo_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QUERY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_CNOMBRE', models.CharField(max_length=64, verbose_name='Nombre')),
                ('QR_CDESCRIPCION', models.CharField(max_length=1024, verbose_name='Descripción')),
                ('QR_FFECHACREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('QR_NHABILITADO', models.BooleanField(default=True)),
                ('QR_CLABEL_FIELDS', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Etiquetas')),
                ('QR_CQUERY', models.TextField(verbose_name='Contenido')),
                ('USER_CREATOR_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='query_user_creator', to=settings.AUTH_USER_MODEL, verbose_name='id usuario creador')),
                ('USER_UPD_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='query_user_upd', to=settings.AUTH_USER_MODEL, verbose_name='id usuario actualizador')),
            ],
            options={
                'db_table': 'QUERY',
            },
        ),
    ]
