# Generated by Django 5.0.4 on 2024-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_empleado_contratista_tarea_financiera',
            name='AEC_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_contratista_tarea_general',
            name='AEC_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_contratista_tarea_ingenieria',
            name='AEC_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_financiera',
            name='AE_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_general',
            name='AE_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_empleado_tarea_ingenieria',
            name='AE_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_recurso_tarea_financiera',
            name='ART_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_recurso_tarea_general',
            name='ART_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='asignacion_recurso_tarea_ingenieria',
            name='ART_COSTO_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total'),
        ),
    ]
