# Generated by Django 5.0.4 on 2024-09-03 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_estado_de_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO_DE_PAGO_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDD_NCANTIDAD', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('EDD_NPRECIO_UNITARIO', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('EDD_NSUBTOTAL', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('EDD_NDESCUENTO', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Descuento')),
                ('EDD_NTOTAL', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('EDD_FFECHA_CREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('EDD_FFECHA_MODIFICACION', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('EDD_CUSUARIO_CREADOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_edp_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('EDD_CUSUARIO_MODIFICADOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_edp_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificador')),
                ('EDD_ESTADO_DE_PAGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='home.estado_de_pago', verbose_name='Estado de Pago')),
                ('EDD_PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_edp', to='home.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Estado de Pago',
                'verbose_name_plural': 'Detalles de Estados de Pago',
                'db_table': 'EDP_DETALLE',
                'unique_together': {('EDD_ESTADO_DE_PAGO', 'EDD_PRODUCTO')},
            },
        ),
    ]
