# Generated by Django 5.1 on 2024-09-04 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_estado_de_pago_detalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UNIDAD_NEGOCIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UN_CCODIGO', models.CharField(max_length=20, unique=True, verbose_name='Código de unidad de negocio')),
                ('UN_CDESCRIPCION', models.CharField(max_length=1024, verbose_name='Descripción de la unidad de negocio')),
                ('UN_BHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('UN_CUSUARIO_CREADOR', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidad_negocio_creador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto_cliente',
            name='PC_CUNIDAD_NEGOCIO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='home.unidad_negocio', verbose_name='Unidad de Negocio'),
        ),
    ]
