# Generated by Django 5.1 on 2024-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_unidad_negocio_proyecto_cliente_pc_cunidad_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad_negocio',
            name='UN_FFECHA_CREACION',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
