# Generated by Django 5.1 on 2024-09-04 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_unidad_negocio_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FICHA_CIERRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FC_JEFE_DE_PROYECTO', models.CharField(max_length=255, null=True, verbose_name='Jefe de Proyecto')),
                ('FC_NUMERO_DE_PROYECTO', models.CharField(max_length=20, verbose_name='Número de Proyecto')),
                ('FC_FECHA_DE_CIERRE', models.DateField(verbose_name='Fecha de Cierre')),
                ('FC_HH_GASTADAS', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas Hombre Gastadas')),
                ('FC_HH_COBRADAS', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas Hombre Cobradas')),
                ('FC_EXCEDENTES', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Excedentes')),
                ('FC_PROYECCION_CON_EL_CLIENTE', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Proyección con el Cliente')),
                ('FC_OBSERVACIONES', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('FC_NOMBRE_DE_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_cierre', to='home.proyecto_cliente', verbose_name='Nombre de Proyecto')),
            ],
            options={
                'verbose_name': 'Ficha de Cierre',
                'verbose_name_plural': 'Fichas de Cierre',
                'db_table': 'FICHA_CIERRE',
            },
        ),
        migrations.CreateModel(
            name='FICHA_CIERRE_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCD_FFECHA_CREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('FCD_FFECHA_MODIFICACION', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('FCD_NACTIVIDAD', models.PositiveIntegerField(verbose_name='Nº Actividad')),
                ('FCD_CACTIVIDAD', models.TextField(verbose_name='Actividad Técnica o Administrativa')),
                ('FCD_CCUMPLIMIENTO', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='¿Cumple?')),
                ('FCD_COBSERVACIONES', models.TextField(blank=True, verbose_name='Observaciones')),
                ('FCD_CUSUARIO_CREADOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_ficha_cierre_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('FCD_CUSUARIO_MODIFICADOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_ficha_cierre_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificador')),
                ('FCD_FICHA_CIERRE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='home.ficha_cierre', verbose_name='Ficha de Cierre')),
            ],
            options={
                'verbose_name': 'Detalle de Ficha de Cierre',
                'verbose_name_plural': 'Detalles de Fichas de Cierre',
                'db_table': 'FICHA_CIERRE_DETALLE',
                'unique_together': {('FCD_FICHA_CIERRE', 'FCD_NACTIVIDAD')},
            },
        ),
    ]
