# Generated by Django 5.1 on 2024-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_ficha_cierre_ficha_cierre_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_cierre',
            name='FC_NUMERO_DE_PROYECTO',
            field=models.CharField(max_length=100, verbose_name='Número de Proyecto'),
        ),
    ]
