# Generated by Django 5.1 on 2024-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_ficha_cierre_fc_numero_de_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_cierre',
            name='FC_EXCEDENTES',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Excedentes'),
        ),
        migrations.AlterField(
            model_name='ficha_cierre',
            name='FC_HH_COBRADAS',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Horas Hombre Cobradas'),
        ),
        migrations.AlterField(
            model_name='ficha_cierre',
            name='FC_HH_GASTADAS',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Horas Hombre Gastadas'),
        ),
        migrations.AlterField(
            model_name='ficha_cierre',
            name='FC_PROYECCION_CON_EL_CLIENTE',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Proyección con el Cliente'),
        ),
    ]
