# Generated by Django 5.0.4 on 2024-09-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_ficha_cierre_fc_excedentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='CO_NTOTAL_MONEDA_EXTRANJERA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total en Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='factura',
            name='FA_NMONTO_PAGADO_MONEDA_EXTRANJERA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Monto Pagado en Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='factura',
            name='FA_NTOTAL_MONEDA_EXTRANJERA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total en Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='orden_venta',
            name='OV_NTOTAL_MONEDA_EXTRANJERA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total en Moneda Extranjera'),
        ),
        migrations.CreateModel(
            name='TIPO_CAMBIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC_CMONEDA', models.CharField(max_length=10, verbose_name='Moneda')),
                ('TC_FFECHA', models.DateTimeField(verbose_name='Fecha de Tipo de Cambio')),
                ('TC_NTASA', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tasa de Cambio')),
                ('FECHA_CREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'db_table': 'TIPO_CAMBIO',
                'unique_together': {('TC_CMONEDA', 'TC_FFECHA')},
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='CO_TIPO_CAMBIO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='home.tipo_cambio', verbose_name='Tipo de Cambio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='FA_TIPO_CAMBIO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='home.tipo_cambio', verbose_name='Tipo de Cambio'),
        ),
        migrations.AddField(
            model_name='orden_venta',
            name='OV_TIPO_CAMBIO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_venta', to='home.tipo_cambio', verbose_name='Tipo de Cambio'),
        ),
    ]
