# Generated by Django 5.0.4 on 2024-09-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_cotizacion_co_ntotal_moneda_extranjera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_cambio',
            name='TC_FFECHA',
            field=models.DateField(verbose_name='Fecha de Tipo de Cambio'),
        ),
    ]
