# Generated by Django 5.0.4 on 2024-09-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_cotizacion_co_ntotal_moneda_extranjera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_venta',
            name='OV_TIPO_CAMBIO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_venta', to='home.tipo_cambio', verbose_name='Tipo de Cambio'),
        ),
    ]
