# Generated by Django 5.1 on 2024-09-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_orden_venta_ov_tipo_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_cliente',
            name='PC_NPRESUPUESTO_MONEDA_EXTRANJERA',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Presupuesto en Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='proyecto_cliente',
            name='PC_TIPO_CAMBIO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='home.tipo_cambio', verbose_name='Tipo de Cambio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='CO_TIPO_CAMBIO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='home.tipo_cambio', verbose_name='Tipo de Cambio'),
        ),
    ]
