# Generated by Django 3.2.6 on 2024-09-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_proyecto_cliente_pc_npresupuesto_moneda_extranjera'),
    ]

    operations = [
        migrations.CreateModel(
            name='MONEDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MO_CMONEDA', models.CharField(max_length=10, verbose_name='Moneda')),
                ('MO_CDESCRIPCION', models.CharField(max_length=255, verbose_name='Descripción')),
                ('MO_BACTIVA', models.BooleanField(default=True, verbose_name='Activo')),
                ('MO_FFECHA_CREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('MO_FFECHA_MODIFICACION', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'MONEDA',
            },
        )
    ]
