# Generated by Django 3.2.6 on 2024-09-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20240909_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='CO_NTOTAL_MONEDA_EXTRANJERA',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='CO_TIPO_CAMBIO',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='FA_NMONTO_PAGADO_MONEDA_EXTRANJERA',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='FA_NTOTAL_MONEDA_EXTRANJERA',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='FA_TIPO_CAMBIO',
        ),
        migrations.RemoveField(
            model_name='orden_venta',
            name='OV_NTOTAL_MONEDA_EXTRANJERA',
        ),
        migrations.RemoveField(
            model_name='orden_venta',
            name='OV_TIPO_CAMBIO',
        ),
        migrations.RemoveField(
            model_name='proyecto_cliente',
            name='PC_TIPO_CAMBIO',
        )
    ]
