# Generated by Django 3.2.6 on 2024-09-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20240909_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_cambio',
            name='TC_CMONEDA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moneda', verbose_name='Moneda'),
        ),
    ]
