# Generated by Django 3.2.6 on 2024-09-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_tipo_cambio_tc_cmoneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_cierre',
            name='FC_MONEDA',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_cierre', to='home.moneda', verbose_name='Moneda'),
        ),
    ]
