# Generated by Django 3.2.6 on 2024-09-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_ficha_cierre_fc_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_cliente',
            name='PC_CLIDER_TECNICO',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Líder Técnico'),
        ),
    ]
