# Generated by Django 3.2.6 on 2024-09-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_proyecto_cliente_pc_clider_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='ET_CESTADO',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='ET_COBSERVACIONES',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='ET_FFECHA_FIN_ESTIMADA',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='ET_FFECHA_FIN_REAL',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='ET_FFECHA_INICIO',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='ET_MONEDA',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='ET_NPRESUPUESTO',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='ET_PROYECTO',
        ),
    ]
