# Generated by Django 3.2.6 on 2024-09-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20240910_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO_TAREA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ET_CNOMBRE', models.CharField(max_length=255, verbose_name='Nombre de la categoría')),
                ('ET_CDESCRIPCION', models.TextField(verbose_name='Descripción de la categoría')),
                ('ET_BACTIVA', models.BooleanField(default=True, verbose_name='Activa')),
                ('ET_FFECHA_CREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ET_FFECHA_MODIFICACION', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Estado de Tarea',
                'verbose_name_plural': 'Estados de Tareas',
                'db_table': 'ESTADO_TAREA',
            },
        ),
        migrations.AlterField(
            model_name='tarea_financiera',
            name='TF_CESTADO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estado_tarea', verbose_name='Estado de la tarea financiera'),
        ),
        migrations.AlterField(
            model_name='tarea_general',
            name='TG_CESTADO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estado_tarea', verbose_name='Estado de la tarea general'),
        ),
        migrations.AlterField(
            model_name='tarea_ingenieria',
            name='TI_CESTADO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estado_tarea', verbose_name='Estado de la tarea de ingeniería'),
        ),
    ]
