# Generated by Django 3.2.6 on 2024-09-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20240910_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea_financiera',
            name='TF_ETAPA',
        ),
        migrations.RemoveField(
            model_name='tarea_general',
            name='TG_ETAPA',
        ),
        migrations.RemoveField(
            model_name='tarea_ingenieria',
            name='TI_ETAPA',
        ),
    ]
