# Generated by Django 3.2.6 on 2024-09-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20240910_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato_cliente',
            name='CC_MONEDA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_cliente', to='home.moneda', verbose_name='Moneda'),
        ),
    ]
