# Generated by Django 5.0.4 on 2024-09-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_estado_de_pago_ep_tarea_financiera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_de_pago',
            name='EP_CNUMERO',
            field=models.CharField(max_length=20, verbose_name='Número de estado de pago'),
        ),
    ]
