# Generated by Django 3.2.6 on 2024-09-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_contrato_cliente_cc_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_cliente',
            name='PC_CONTRATO_CLIENTE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='home.contrato_cliente', verbose_name='Contrato Cliente'),
        ),
    ]
