# Generated by Django 3.2.6 on 2024-09-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_proyecto_cliente_pc_contrato_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO_TAREA_FINANCIERA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ET_CNOMBRE', models.CharField(max_length=255, verbose_name='Nombre de la tarea')),
                ('ET_CDESCRIPCION', models.TextField(verbose_name='Descripción de la tarea')),
                ('ET_BACTIVA', models.BooleanField(default=True, verbose_name='Activa')),
                ('ET_FFECHA_CREACION', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ET_FFECHA_MODIFICACION', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Estado de Tarea Financiera',
                'verbose_name_plural': 'Estados de Tareas Financieras',
                'db_table': 'ESTADO_TAREA_FINANCIERA',
            },
        ),
        migrations.AddField(
            model_name='tarea_financiera',
            name='TF_BCOBRO_EMITIDO',
            field=models.BooleanField(default=False, verbose_name='Cobro Emitido'),
        ),
        migrations.AddField(
            model_name='tarea_financiera',
            name='TF_FFECHAPAGADO',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha pagado'),
        ),
        migrations.AddField(
            model_name='tarea_financiera',
            name='TF_NMONTOPAGADO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Pagado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado_tarea',
            name='ET_CDESCRIPCION',
            field=models.TextField(verbose_name='Descripción de la tarea'),
        ),
        migrations.AlterField(
            model_name='estado_tarea',
            name='ET_CNOMBRE',
            field=models.CharField(max_length=255, verbose_name='Nombre de la tarea'),
        ),
        migrations.AlterField(
            model_name='tarea_financiera',
            name='TF_CESTADO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estado_tarea_financiera', verbose_name='Estado de la tarea financiera'),
        ),
    ]
