# Generated by Django 5.0.4 on 2024-09-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_estado_de_pago_ep_cnumero'),
        ('home', '0039_auto_20240923_1230'),
    ]

    operations = [
    ]
