# Generated by Django 2.1.15 on 2024-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_merge_20240923_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='COSTOS_PERSONA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CP_CNOMBRE', models.CharField(max_length=255, verbose_name='Nombre')),
                ('CP_CCODIGO', models.CharField(max_length=20, verbose_name='Código')),
                ('CP_NAÑO', models.IntegerField(verbose_name='Año')),
                ('CP_NMES', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=20, verbose_name='Mes')),
                ('CP_NVALOR', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('CP_CMONEDA', models.CharField(max_length=10, verbose_name='Tipo de Moneda')),
            ],
            options={
                'verbose_name': 'Costo Personal',
                'verbose_name_plural': 'Costos Personal',
                'db_table': 'COSTOS_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='HH_CONTROL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HH_CONTROL_ID', models.IntegerField(blank=True, null=True)),
                ('HH_CONTROL_USER_ID', models.CharField(max_length=15)),
                ('HH_CONTROL_PROY_ID', models.CharField(max_length=10)),
                ('HH_CONTROL_PCOD', models.CharField(blank=True, max_length=1, null=True)),
                ('HH_CONTROL_ODS_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('HH_CONTROL_DET_ID', models.CharField(blank=True, max_length=55, null=True)),
                ('HH_CONTROL_REV_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('HH_CONTROL_GLOSA_DESC', models.TextField(blank=True, null=True)),
                ('HH_CONTROL_FECHA', models.DateField(blank=True, null=True)),
                ('HH_CONTROL_HORAS', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Control de Horas',
                'verbose_name_plural': 'Controles de Horas',
                'db_table': 'HH_CONTROL',
            },
        )
    ]
