# Generated by Django 5.1 on 2024-09-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20240926_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_cliente',
            name='PC_CCODIGO',
            field=models.CharField(max_length=100, verbose_name='Código de proyecto'),
        ),
    ]
